### PR TITLE
Add utility to list JSX event handlers

### PR DESCRIPTION
**Pull request by jessebeach**
Provides a list of common JSX event handlers as a flat list and grouped into types.

### CODE REVIEW

**Comment by evcohen** [comment]
I guess there are eslint issues in the build, but otherwise LGTM. Can you also update README? thanks!

**Comment by jessebeach** [comment]
@evcohen gtg. I don't have merge privileges on this repo, so I defer to you :)

**Comment by jessebeach** [comment]
I'll PR an update in eslint-plugin-jsx-a11y if you publish a point release.

**Comment by evcohen** [comment]
[v1.4.0](https://github.com/evcohen/jsx-ast-utils/releases/tag/1.4.0) published

**Pull request merged**
